export const actionTypes = {  
  FETCH_MEMBER_BY_ID_COMPLETED: 'FETCH_MEMBER_BY_ID_COMPLETED',
  UPDATE_MEMBER_FIELD: 'UPDATE_MEMBER_FIELD',
  SAVE_MEMBER: 'SAVE_MEMBER',
  FETCH_REPOSITORIES_COMPLETED:'FETCH_REPOSITORIES_COMPLETED',
  FETCH_MEMBER_REQUEST_START : 'FETCH_MEMBER_START',
  FETCH_MEMBER_REQUEST_COMPLETED : 'FETCH_MEMBER_REQUEST',
};
